local t = Def.ActorFrame{
	-- P1 TIME
	LoadActor("_HIBANA")..{
	InitCommand=function(self)
		self:x(12):y(SCREEN_CENTER_Y-140)
	end;
	OnCommand=function(self)
		self:addy(430):rotationz(-90):sleep(.25):linear(.2):addy(-430):linear(.2):addy(-300)
	end;
	};
	LoadActor("_HIBANA")..{
	InitCommand=function(self)
		self:x(16):y(SCREEN_CENTER_Y+10)
	end;
	OnCommand=function(self)
		self:addy(-430):rotationz(90):sleep(.25):linear(.2):addy(430):linear(.05):addy(56):sleep(.03):addy(999)
	end;
	};
	-- P2 TIME
	LoadActor("_HIBANA")..{
	InitCommand=function(self)
		self:x(628):y(SCREEN_CENTER_Y-140)
	end;
	OnCommand=function(self)
		self:addy(430):rotationz(-90):sleep(.25):linear(.2):addy(-430):linear(.2):addy(-300)
	end;
	};
	LoadActor("_HIBANA")..{
	InitCommand=function(self)
		self:x(624):y(SCREEN_CENTER_Y+10)
	end;
	OnCommand=function(self)
		self:addy(-430):rotationz(90):sleep(.25):linear(.2):addy(430):linear(.05):addy(56):sleep(.03):addy(999)
	end;
	};
	-- 
	LoadActor("FLARE")..{
	InitCommand=function(self)
		self:x(249):y(SCREEN_CENTER_Y+194):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(.3):diffusealpha(1):sleep(.05):linear(.05):diffusealpha(0)
	end;
	};
	LoadActor("SPARK_EF2")..{
	InitCommand=function(self)
		self:horizalign(right):x(240):y(SCREEN_CENTER_Y+190):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:zoom(.4):diffusealpha(0):sleep(.3):diffusealpha(1):linear(.1):y(420):zoom(.9):linear(.1):zoom(1):diffusealpha(0)
	end;
	};
	
	LoadActor("FLARE")..{
	InitCommand=function(self)
		self:x(391):y(SCREEN_CENTER_Y+194):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(.3):diffusealpha(1):sleep(.05):linear(.05):diffusealpha(0)
	end;
	};
	LoadActor("SPARK_EF3")..{
	InitCommand=function(self)
		self:horizalign(left):x(400):y(SCREEN_CENTER_Y+190):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:zoom(.4):diffusealpha(0):sleep(.3):diffusealpha(1):linear(.1):y(420):zoom(.9):linear(.1):zoom(1):diffusealpha(0)
	end;
	};
	--layer5
	LoadActor("_HIBANA")..{
	InitCommand=function(self)
		self:x(236):y(SCREEN_CENTER_Y+172):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:addy(-5):addx(-280):sleep(.2):linear(.1):addx(180):linear(.05):addy(5):addx(20):linear(.1):addx(80):sleep(0):addy(999)
	end;
	};
	LoadActor("P_SHOCK")..{
	InitCommand=function(self)
		self:x(236):y(SCREEN_CENTER_Y+172):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):zoom(.4):sleep(.40):diffusealpha(1):linear(.1):zoom(.9):linear(.05):zoom(1.5):diffusealpha(0)
	end;
	};
	LoadActor("P_SHOCK")..{
	InitCommand=function(self)
		self:x(236):y(SCREEN_CENTER_Y+172):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):zoom(.4):sleep(.40):diffusealpha(1):linear(.1):zoom(.9):linear(.05):zoom(1.5):diffusealpha(0)
	end;
	};
	
	--layer8
	LoadActor("_HIBANA")..{
	InitCommand=function(self)
		self:x(404):y(SCREEN_CENTER_Y+172):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:addy(-5):addx(280):sleep(.2):linear(.1):addx(-180):linear(.05):addy(5):addx(-20):linear(.1):addx(-80):sleep(0):addy(999)
	end;
	};
	LoadActor("P_SHOCK")..{
	InitCommand=function(self)
		self:x(404):y(SCREEN_CENTER_Y+172):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):zoom(.4):sleep(.40):diffusealpha(1):linear(.1):zoom(.9):linear(.05):zoom(1.5):diffusealpha(0)
	end;
	};
	LoadActor("P_SHOCK")..{
	InitCommand=function(self)
		self:x(404):y(SCREEN_CENTER_Y+172):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):zoom(.4):sleep(.40):diffusealpha(1):linear(.1):zoom(.9):linear(.05):zoom(1.5):diffusealpha(0)
	end;
	};
	
	--layer11
	LoadActor("SPARK_EF.png")..{
	InitCommand=function(self)
		self:x(130):y(SCREEN_CENTER_Y+167):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(.3):diffusealpha(1):linear(.2):zoomx(30):linear(.2):diffusealpha(0)
	end;
	};
	LoadActor("SPARK_EF.png")..{
	InitCommand=function(self)
		self:x(510):y(SCREEN_CENTER_Y+167):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(.3):diffusealpha(1):linear(.2):zoomx(30):linear(.2):diffusealpha(0)
	end;
	};
	
	--layer13
	LoadActor("SPARK_EF3")..{
	InitCommand=function(self)
		self:horizalign(left):x(30):y(SCREEN_CENTER_Y+60):blend('BlendMode_Add'):rotationz(90)
	end;
	OnCommand=function(self)
		self:zoom(.4):diffusealpha(0):sleep(.52):diffusealpha(1):linear(.1):zoom(1):linear(.02):zoom(1.4):diffusealpha(0)
	end;
	};
	LoadActor("P_SHOCK")..{
	InitCommand=function(self)
		self:x(20):y(SCREEN_CENTER_Y-60):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):zoom(.4):sleep(.4):diffusealpha(1):linear(.1):zoom(1):linear(.05):zoom(1.4):diffusealpha(0)
	end;
	};
	LoadActor("SPARK_EF.png")..{
	InitCommand=function(self)
		self:x(20):y(SCREEN_CENTER_Y-60):blend('BlendMode_Add'):rotationz(90)
	end;
	OnCommand=function(self)
		self:zoomx(0):sleep(.4):linear(.1):zoomx(30):linear(.3):diffusealpha(0)
	end;
	};
	
	--layer20
	LoadActor("SPARK_EF2")..{
	InitCommand=function(self)
		self:horizalign(right):x(610):y(SCREEN_CENTER_Y+60):blend('BlendMode_Add'):rotationz(-90)
	end;
	OnCommand=function(self)
		self:zoom(.4):diffusealpha(0):sleep(.52):diffusealpha(1):linear(.1):zoom(1):linear(.02):zoom(1.4):diffusealpha(0)
	end;
	};
	LoadActor("P_SHOCK")..{
	InitCommand=function(self)
		self:x(620):y(SCREEN_CENTER_Y-60):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):zoom(.4):sleep(.4):diffusealpha(1):linear(.1):zoom(1):linear(.05):zoom(1.4):diffusealpha(0)
	end;
	};
	LoadActor("SPARK_EF.png")..{
	InitCommand=function(self)
		self:x(620):y(SCREEN_CENTER_Y-60):blend('BlendMode_Add'):rotationz(90)
	end;
	OnCommand=function(self)
		self:zoomx(0):sleep(.4):linear(.1):zoomx(30):linear(.3):diffusealpha(0)
	end;
	};
	
};

return t;