local t = Def.ActorFrame {
	LoadActor("INFO.png")..{
		InitCommand=function(self)
			self:x(WideScale(SCREEN_CENTER_X-256,SCREEN_CENTER_X-356)):y(SCREEN_CENTER_Y-195)
		end;
		OnCommand=function(self)
			self:diffusealpha(0):sleep(0.5):diffusealpha(1)
		end;
	};
	LoadActor("SETSUMEI2.png")..{
		InitCommand=function(self)
			self:x(WideScale(SCREEN_CENTER_X-162,SCREEN_CENTER_X-262)):y(SCREEN_CENTER_Y-179)
		end;
		OnCommand=function(self)
			self:cropright(1):sleep(0.6):linear(0.4):cropright(0)
		end;
	};
	LoadActor("BUTTON.png")..{
		InitCommand=function(self)
			self:x(WideScale(SCREEN_CENTER_X-298,SCREEN_CENTER_X-398)):y(SCREEN_CENTER_Y-161)
		end;
		OnCommand=function(self)
			self:zoom(0):sleep(0.6):linear(0.2):zoom(1)
		end;
	};
	LoadActor("B_START.png")..{
		InitCommand=function(self)
			self:x(WideScale(SCREEN_CENTER_X-183,SCREEN_CENTER_X-283)):y(SCREEN_CENTER_Y-161)
		end;
		OnCommand=function(self)
			self:cropright(1):sleep(0.6):linear(0.4):cropright(0)
		end;
	};
	LoadActor("BUTTON.png")..{
		InitCommand=function(self)
			self:x(WideScale(SCREEN_CENTER_X-298,SCREEN_CENTER_X-398)):y(SCREEN_CENTER_Y-144)
		end;
		OnCommand=function(self)
			self:zoom(0):sleep(0.65):linear(0.2):zoom(1)
		end;
	};
	LoadActor("B_START.png")..{
		InitCommand=function(self)
			self:x(WideScale(SCREEN_CENTER_X-183,SCREEN_CENTER_X-283)):y(SCREEN_CENTER_Y-161)
		end;
		OnCommand=function(self)
			self:cropright(1):sleep(0.6):linear(0.4):cropright(0)
		end;
	};
	LoadActor("B_START_FLASH.png")..{
		InitCommand=function(self)
			self:x(WideScale(SCREEN_CENTER_X-154,SCREEN_CENTER_X-254)):y(SCREEN_CENTER_Y-161):diffusealpha(0):sleep(2):diffusealpha(1)
		end;
		OnCommand=function(self)
			self:diffusealpha(0):playcommand("Animate")
		end;
		AnimateCommand=function(self)
			self:blend('BlendMode_Add'):diffusealpha(0.6):cropright(1):linear(1):cropright(0):linear(0.6):diffusealpha(0):sleep(.4):queuecommand("Animate")
		end;
	};
	LoadActor("B_VEFX.png")..{
		InitCommand=function(self)
			self:x(WideScale(SCREEN_CENTER_X-203,SCREEN_CENTER_X-303)):y(SCREEN_CENTER_Y-144)
		end;
		OnCommand=function(self)
			self:cropright(1):sleep(0.65):linear(0.4):cropright(0)
		end;
	};
	LoadActor("B_VEFX_FLASH.png")..{
		InitCommand=function(self)
			self:x(WideScale(SCREEN_CENTER_X-176,SCREEN_CENTER_X-276)):y(SCREEN_CENTER_Y-144):diffusealpha(0):sleep(2):diffusealpha(1)
		end;
		OnCommand=function(self)
			self:diffusealpha(0):playcommand("Animate")
		end;
		AnimateCommand=function(self)
			self:blend('BlendMode_Add'):diffusealpha(0.6):cropright(1):linear(1):cropright(0):linear(0.6):diffusealpha(0):sleep(.4):queuecommand("Animate")
		end;
	};
};

return t;