local t = Def.ActorFrame{
	LoadActor("bg_color")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y):diffusealpha(8)
	end;
	};
	LoadActor("bg2")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y):diffusealpha(8)
	end;
	OnCommand=function(self)
		self:zoom(2):diffusealpha(.8):linear(2.5):zoom(1)
	end;
	};
	LoadActor("bg.png")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:zoom(3):diffusealpha(.3):linear(3):zoom(2):diffusealpha(0)
	end;
	};
	LoadActor("1")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y-188)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):addy(200):linear(.3):addy(-200):diffusealpha(.8)
	end;
	};
	LoadActor("2.png")..{
	InitCommand=function(self)
		self:x(290):y(SCREEN_CENTER_Y-57)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):addx(-200):linear(.3):addx(200):diffusealpha(.8)
	end;
	};
	LoadActor("3.png")..{
	InitCommand=function(self)
		self:x(283):y(SCREEN_CENTER_Y+33)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):addy(-200):linear(.3):addy(200):diffusealpha(.8)
	end;
	};
	LoadActor("4.png")..{
	InitCommand=function(self)
		self:x(600):y(SCREEN_CENTER_Y-50)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):addx(100):linear(.2):addx(-100):diffusealpha(.8)
	end;
	};
	LoadActor("5.png")..{
	InitCommand=function(self)
		self:x(154):y(SCREEN_CENTER_Y+139)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):addx(-300):sleep(.1):linear(.3):addx(300):diffusealpha(.8)
	end;
	};
	LoadActor("glow.png")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:zoom(2):diffusealpha(.2)
	end;
	};
	LoadActor("gradient.png")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y)
	end;
	OnCommand=function(self)
		self:diffusealpha(1)
	end;
	};
	LoadActor("ring.png")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y)
	end;
	OnCommand=function(self)
		self:zoom(.8):diffusealpha(0):linear(.3):zoom(1):diffusealpha(1):sleep(2.8):diffusealpha(0)
	end;
	};
	LoadActor("MUSIC_WAKU_BG")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y-46):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:texcoordvelocity(-.1,0):diffusealpha(0.8):zoomy(0):sleep(.3):linear(.2):zoomy(1.05):linear(.1):zoomy(1)
	end;
	};
	LoadActor("_songtitle")..{
	};
	LoadActor("_coursetitle")..{
	};
	Def.Quad{
	InitCommand=function(self)
		self:diffuse(color("#FFFFFF")):x(320):y(SCREEN_CENTER_Y):zoomtowidth(SCREEN_WIDTH):zoomtoheight(SCREEN_HEIGHT):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:linear(.2):diffusealpha(0)
	end;
	};
	Def.Quad{
	InitCommand=function(self)
		self:diffuse(color("#000000")):x(320):y(SCREEN_CENTER_Y):zoomtowidth(SCREEN_WIDTH):zoomtoheight(SCREEN_HEIGHT)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(2):linear(0.4):diffusealpha(.4)
	end;
	};
	-------------------------------------
	LoadActor("bg.png")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(2.4):diffusealpha(.6):linear(.6):zoom(.6)
	end;
	};
	LoadActor("bg.png")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(2.4):diffusealpha(.6):linear(.6):zoom(1.3)
	end;
	};
	LoadActor("bg.png")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(2.4):diffusealpha(.6):linear(.6):zoom(2)
	end;
	};
	--------------------------------------
	-- OPTIONS ---------------------------
	LoadActor("OPTIONS")..{
	};
	--------------------------------------
	--Layer180
	LoadActor("glow.png")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:zoom(2):zoomx(3):diffusealpha(0):sleep(2.4):diffusealpha(1):linear(.5):diffusealpha(0)
	end;
	};
	LoadActor("glow.png")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y):blend('BlendMode_Add')
	end;
	OnCommand=function(self)
		self:zoom(2):zoomx(3):diffusealpha(0):sleep(2.4):diffusealpha(1):linear(.5):diffusealpha(0)
	end;
	};
	Def.Quad{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y):zoomtowidth(SCREEN_WIDTH):zoomtoheight(SCREEN_HEIGHT):diffuse(color("#000000"))
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(2.5):linear(0.3):diffusealpha(1)
	end;
	};
};

return t;