local t = Def.ActorFrame{
	LoadActor("LOOP_BG2")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y)
	end;
	OnCommand=function(self)
		self:zoomy(1.1):diffusealpha(.6):texcoordvelocity(0,-.1)
	end;
	};
	LoadActor("LOOP_BG3")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y)
	end;
	OnCommand=function(self)
		self:diffusealpha(.2):texcoordvelocity(0,-.2)
	end;
	};
	LoadActor("LOOP_BG1")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y)
	end;
	OnCommand=function(self)
		self:diffusealpha(.2):texcoordvelocity(0,-.3)
	end;
	};
	LoadActor("LOOP_BG2")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y)
	end;
	OnCommand=function(self)
		self:diffuse(0,0,0,1):sleep(.3):diffusealpha(0)
	end;
	};
	LoadActor("LOOP_BG2")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y)
	end;
	OnCommand=function(self)
		self:texcoordvelocity(0,-1):zoomy(100):sleep(.3):diffusealpha(0)
	end;
	};
	LoadActor("REDBALL")..{
	InitCommand=function(self)
		self:blend('BlendMode_Add'):x(320):y(SCREEN_CENTER_Y)
	end;
	OnCommand=function(self)
		self:diffusealpha(1):zoom(3):zoomx(100):zoomy(4)
	end;
	};
	LoadActor("ring")..{
	InitCommand=function(self)
		self:x(320):y(SCREEN_CENTER_Y)
	end;
	OnCommand=function(self)
		self:zoom(.5):diffusealpha(0):linear(.4):diffusealpha(1):zoom(1)
	end;
	};
};

return t;