local t = Def.ActorFrame{
	LoadActor("failed")..{
	InitCommand=function(self)
		self:x(320):y(140)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):zoomx(20):sleep(0.5):linear(0.2):diffusealpha(1):zoomx(1):sleep(0.5):linear(0.1):diffusealpha(0)
	end;
	};
	LoadActor("failed")..{
	InitCommand=function(self)
		self:blend('BlendMode_Add'):x(320):y(140)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(1.1):linear(0.2):diffusealpha(1):linear(0.1):zoomy(0)
	end;
	};
	LoadActor("line")..{
	InitCommand=function(self)
		self:x(320):y(140)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):sleep(1.3):linear(0.1):diffusealpha(1):linear(0.2):zoomx(20):diffusealpha(0)
	end;
	};
	LoadActor("line")..{
	InitCommand=function(self)
		self:zoomtowidth(380):x(380):y(190)
	end;
	OnCommand=function(self)
		self:x(-640):sleep(0.8):linear(0.3):x(900)
	end;
	};
	LoadActor("line")..{
	InitCommand=function(self)
		self:zoomtowidth(380):x(380):y(90)
	end;
	OnCommand=function(self)
		self:x(900):sleep(0.8):linear(0.3):x(-640)
	end;
	};
	LoadActor("DJLV1")..{
	InitCommand=function(self)
		self:x(140):y(188)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):zoomy(0):sleep(2):linear(0.2):diffusealpha(1):zoomy(1.2):linear(0.1):zoomy(1)
	end;
	Condition=GAMESTATE:IsSideJoined(PLAYER_1);
	};
	LoadActor("DJLV2")..{
	InitCommand=function(self)
		self:x(501):y(188)
	end;
	OnCommand=function(self)
		self:diffusealpha(0):zoomy(0):sleep(2):linear(0.2):diffusealpha(1):zoomy(1.2):linear(0.1):zoomy(1)
	end;
	Condition=GAMESTATE:IsSideJoined(PLAYER_2);
	};
};

return t;