local t = Def.ActorFrame {
	LoadActor("BG_MUSIC.png")..{
		InitCommand=function(self)
			self:x(320):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:diffusealpha(0):addx(-15):addy(-15):linear(0.5):addx(15):addy(15):diffusealpha(0.8)
		end;
	};
	LoadActor("UP_PARTS.png")..{
		InitCommand=function(self)
			self:x(299):y(SCREEN_CENTER_Y-114)
		end;
		OnCommand=function(self)
			self:blend('BlendMode_Add'):diffusealpha(0.8):addy(400):sleep(0.1):linear(0.5):addy(-350):linear(0.15):addy(-50):linear(0.4):diffusealpha(0)
		end;
	};
	LoadActor("BG_FLASH1.png")..{
		InitCommand=function(self)
			self:x(40):y(SCREEN_CENTER_Y-40)
		end;
		OnCommand=function(self)
			self:blend('BlendMode_Add'):diffusealpha(0):sleep(0.5):diffusealpha(0.7):sleep(0.1):diffusealpha(0)
		end;
	};
	LoadActor("BG_FLASH2.png")..{
		InitCommand=function(self)
			self:x(217):y(SCREEN_CENTER_Y-73)
		end;
		OnCommand=function(self)
			self:blend('BlendMode_Add'):diffusealpha(0):sleep(0.55):diffusealpha(0.7):sleep(0.1):diffusealpha(0)
		end;
	};
	LoadActor("BG_FLASH3.png")..{
		InitCommand=function(self)
			self:x(204):y(SCREEN_CENTER_Y+24)
		end;
		OnCommand=function(self)
			self:blend('BlendMode_Add'):diffusealpha(0):sleep(0.6):diffusealpha(0.7):sleep(0.1):diffusealpha(0)
		end;
	};
	LoadActor("BG_FLASH4.png")..{
		InitCommand=function(self)
			self:x(43):y(SCREEN_CENTER_Y+150)
		end;
		OnCommand=function(self)
			self:blend('BlendMode_Add'):diffusealpha(0):sleep(0.65):diffusealpha(0.7):sleep(0.1):diffusealpha(0)
		end;
	};
	LoadActor("BG_FLASH5.png")..{
		InitCommand=function(self)
			self:x(252):y(SCREEN_CENTER_Y+82)
		end;
		OnCommand=function(self)
			self:blend('BlendMode_Add'):diffusealpha(0):sleep(0.7):diffusealpha(0.7):sleep(0.1):diffusealpha(0)
		end;
	};
	LoadActor("DIFF_CHANGE.png")..{
		InitCommand=function(self)
			self:x(640):y(SCREEN_CENTER_Y-9):horizalign(right)
		end;
		OnCommand=function(self)
			self:blend('BlendMode_Add'):addx(300):linear(.3):addx(-300):linear(.2):diffusealpha(.5)
		end;
	};
};
return t;