local t = Def.ActorFrame {
	LoadActor("failed.ogg")..{
		StartTransitioningCommand=function(self)
			self:play()
		end;
	};
	LoadActor("left.png")..{
		InitCommand=function(self)
			self:horizalign(left):x(0):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:addx(-400):linear(0.4):addx(400):linear(0.1):addx(-5):linear(0.1):addx(5)
		end;
	};
	LoadActor("lock-left.png")..{
		InitCommand=function(self)
			self:horizalign(left):x(0):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:addx(-400):linear(0.4):addx(400):linear(0.1):addx(-5):linear(0.1):addx(5):sleep(.3):linear(.2):addx(-10)
		end;
	};
	LoadActor("right.png")..{
		InitCommand=function(self)
			self:horizalign(right):x(640):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:addx(400):linear(0.4):addx(-400):linear(0.1):addx(5):linear(0.1):addx(-5)
		end;
	};
	LoadActor("lock-right.png")..{
		InitCommand=function(self)
			self:horizalign(right):x(640):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:addx(400):linear(0.4):addx(-400):linear(0.1):addx(5):linear(0.1):addx(-5):sleep(.3):linear(.2):addx(10)
		end;
	};
	LoadActor("FLARE.png")..{
		InitCommand=function(self)
			self:blend('BlendMode_Add'):x(320):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:zoom(10):zoomy(30):diffusealpha(0):sleep(.1):linear(0.2):diffusealpha(1):linear(0.1):zoomx(0.2):sleep(.1):diffusealpha(0)
		end;
	};
	LoadActor("FLARE.png")..{
		InitCommand=function(self)
			self:blend('BlendMode_Add'):x(320):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:zoom(10):zoomy(30):diffusealpha(0):sleep(.1):linear(0.2):diffusealpha(1):linear(0.1):zoomx(0.2):sleep(.1):diffusealpha(0)
		end;
	};
	LoadActor("FLARE.png")..{
		InitCommand=function(self)
			self:blend('BlendMode_Add'):x(320):y(SCREEN_CENTER_Y-56)
		end;
		OnCommand=function(self)
			self:diffusealpha(0):sleep(.4):diffusealpha(1):sleep(.1):diffusealpha(0)
		end;
	};
	LoadActor("SPARK_EF2.png")..{
		InitCommand=function(self)
			self:horizalign(right):vertalign(top):blend('BlendMode_Add'):x(320):y(SCREEN_CENTER_Y-72)
		end;
		OnCommand=function(self)
			self:rotationz(-10):zoom(0):sleep(.3):linear(.2):zoom(1):diffusealpha(1):linear(0):diffusealpha(0)
		end;
	};
	LoadActor("FLARE.png")..{
		InitCommand=function(self)
			self:blend('BlendMode_Add'):x(320):y(SCREEN_CENTER_Y+56)
		end;
		OnCommand=function(self)
			self:diffusealpha(0):sleep(.4):diffusealpha(1):sleep(.1):diffusealpha(0)
		end;
	};
	LoadActor("SPARK_EF1.png")..{
		InitCommand=function(self)
			self:horizalign(right):vertalign(top):blend('BlendMode_Add'):x(320):y(SCREEN_CENTER_Y+72)
		end;
		OnCommand=function(self)
			self:rotationz(50):zoom(0):sleep(.3):linear(.2):zoom(1):diffusealpha(1):linear(0):diffusealpha(0)
		end;
	};
	LoadActor("GREENLINE.png")..{
		InitCommand=function(self)
			self:blend('BlendMode_Add'):x(140):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:cropleft(1):sleep(.7):linear(.5):cropleft(0)
		end;
	};
	LoadActor("GREENLINE.png")..{
		InitCommand=function(self)
			self:blend('BlendMode_Add'):x(493):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:cropright(1):sleep(.7):linear(.5):cropright(0)
		end;
	};
	Def.Quad{
		InitCommand=function(self)
			self:x(320):y(SCREEN_CENTER_Y):zoomtowidth(SCREEN_WIDTH):zoomtoheight(SCREEN_HEIGHT):diffuse(color("#000000"))
		end;
		OnCommand=function(self)
			self:diffusealpha(0):sleep(2):linear(.3):diffusealpha(1)
		end;
	};
};
return t;
